### ISSUE TITLE
Adding IK to a Skinned Arm

### ISSUE THREAD

**Issue by tomatrow** [jsantell/THREE.IK#8]
Hello, 

I'm trying to add IK to a simple skinned rectangular arm. 

I forked this repository and tried to do that in the examples directory [here](https://github.com/tomatrow/THREE.IK) under `/THREE.IK/examples/arm.html`. 

I've been having trouble the axis. It seems the skin and the armature don't align when we solve the system.

I suppose I'll turn this into a pull request for a new example once it's working.

**Comment by jsantell** [comment]
Here's an [example using SkinnedMesh](https://jsantell.github.io/THREE.IK/examples/#skinned-mesh) using a utility to flip a model's forward from -Z to +Z
